env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
  project: ["tsconfig.json"]
plugins:
  - '@typescript-eslint'
rules: 
  '@typescript-eslint/no-explicit-any': 0
  '@typescript-eslint/no-floating-promises': 
    - 'error'
  '@typescript-eslint/no-misused-promises':
    - 'error'